#ADTPro.properties
#Sun Feb 09 18:04:22 CET 2025
CommPortBootstrapPacing=250
CommPortBootstrapSpeed=9600
CommPortSpeed=115200
CoordH=228
CoordW=324
CoordX=606
CoordY=318
HardwareHandshaking=false
TraceEnabled=false
WorkingDirectory=D\:\\Git\\Retro\\git-retro\\apple\\AppleII\\ADTPro-2.1.0\\
