import art
import serial
import sys
import time

def load(path):
    with open(path) as f:
        s = f.read()
    rows = s.split("\n")
    max = 0
    for row in rows:
        if len(row) > max:
            max = len(row)
    s = ""
    for row in rows:
        s += row
        for _ in range(max - len(row)):
            s += " "
        s += "\n"
    return s

s = "\n\n"
s += art.text2art("Personal", "big")
s += "\n"
s += art.text2art("Computer", "big")
s += "\n"
s += art.text2art("History", "big")
s += "\n\n"
s += art.text2art("1977")
s += "\n\n"
while True:
    s += "The Trinity Apple Tandy Commodore"
    s += "\n\n"
    s += "Apple ]["
    s += "\n"
    s += "MOS 6502 @ 1 MHz 4Ko, 8 bits, K7, 1300$, 100K units sold"
    s += "\n"
    s += "More than 4M units sold until 1993"
    s += "\n\n"
    s += load("ascii/apple.txt")
    s += "\n\n"
    s += load("ascii/apple2.txt")
    s += "\n\n"
    s += "Steve Jobs Apple co-founder"
    s += "\n\n"
    s += load("ascii/stevejobs.txt")
    s += "\n\n"
    s += "Steve Wozniak (Woz) Apple co-founder"
    s += "\n\n"
    s += load("ascii/wozniak.txt")
    s += "\n\n"
    s += "Tandy TRS-80"
    s += "\n"
    s += "Zilog Z80 @ 1.8 MHz 4 Ko, 8 bits, K7, 800$, 400K units sold"
    s += "\n"
    s += "More than 1M units sold until 1983"
    s += "\n\n"
    s += load("ascii/simple_computer.txt")
    s += "\n\n"
    s += "Commodore PET 2001"
    s += "\n"
    s += "MOS 6502 @ 1 MHz 4 Ko, 8 bits, K7, 800$, 50K units sold"
    s += "\n"
    s += load("ascii/pet.txt")
    s += "\n\n"
    s += "Atari VCS 2600"
    s += "\n"
    s += "First video game console, 27M units sold"
    s += "\n"
    s += load("ascii/atari_logo.txt")
    s += "\n\n"
    s += load("ascii/atari_vcs.txt")
    s += "\n\n"
    s += load("ascii/pacman.txt")
    s += "\n\n"
    s += art.text2art("1978")
    s += "\n\n"
    s += "Floppy Disc 5\"1/4 120 Ko, sold by Apple, Tandy & Commodore"
    s += "\n\n"
    s += load("ascii/floppy.txt")
    s += "\n\n"
    s += art.text2art("1979")
    s += "\n\n"
    s += "Apple ][+"
    s += "\n"
    s += "MOS 6502 @ 1 MHz 16 Ko, 8 bits, FDD 5\"1/4, 1200$ + 1000$\n"
    s += "800K units sold"
    s += "\n\n"
    s += load("ascii/apple2e.txt")
    s += "\n\n"
    s += "Texas Instrument TI99/4"
    s += "\n"
    s += "TI TMS 9900 @ 3 MHz 16 Ko, 8/16 bits, K7, 1200$, 20K units sold"
    s += "\n"
    s += "The first 16 bits computer"
    s += "\n\n"
    s += "Atari 400 & 800"
    s += "\n"
    s += "MOS 6502 @ 1.8 MHz 8 Ko, 8 bits, K7, 100$ - 200$, 4M units sold"
    s += "\n"
    s += "Atari success story"
    s += "\n\n"
    s += load("ascii/atari800.txt")
    s += "\n\n"
    s += art.text2art("1980")
    s += "\n\n"
    s += "France Telecom Minitel"
    s += "\n"
    s += "Intel 8052, 8 bits, modem, 0F, 30M units sold"
    s += "\n"
    s += "Every french home have a minitel\n"
    s += art.text2art("MINITEL")
    s += "\n\n"
    s += "Sinclair ZX80"
    s += "\n"
    s += "Zilog Z80 @ 3 MHz 1 Ko, 8 bits, K7, 200$, 100K units sold"
    s += "\n\n"
    s += "Commodore VIC20"
    s += "\n"
    s += "MOS 6502 @ 1 MHz 5 Ko, 8 bits, K7 + FDD 5\"1/4, 300$, 3M units sold"
    s += "\n"
    s += "Low cost, large success"
    s += "\n"
    s += "Jack Tramiel Commodore founder"
    s += "\n"
    s += load("ascii/tramiel.txt")
    s += "\n\n"
    s += art.text2art("1981")
    s += "\n\n"
    s += "Sinclair ZX81"
    s += "\n"
    s += "Zilog Z80 @ 3 MHz 1 Ko, 8 bits, K7, 200$, 1500K units sold"
    s += "\n"
    s += "Sir Clive Sinclair"
    s += "\n\n"
    s += load("ascii/sir_clive_sinclair.txt")
    s += "\n\n"
    s += "IBM PC 5150"
    s += "\n"
    s += "Intel 8088 @ 4 MHz 64 Ko, 8/16 bits, 2 FDD 5\"1/4, 1500$"
    s += "\n"
    s += "The first PC"
    s += "\n\n"
    s += load("ascii/pc.txt")
    s += "\n\n"
    s += art.text2art("1982")
    s += "\n\n"
    s += "The Golden Age"
    s += "\n\n"
    s += "Sinclair ZX Spectrum"
    s += "\n"
    s += "Zilog Z80 @ 3 MHz 16 Ko, 8 bits, K7, 250$, 5M units sold"
    s += "\n"
    s += "Very big success"
    s += "\n\n"
    s += "Commodore 64"
    s += "\n"
    s += "MOS 6502 @ 1 MHz 64 Ko, 8 bits, K7 + FDD 5\"1/4, 600$, 25M units sold"
    s += "\n"
    s += "Low cost, large success"
    s += "\n"
    s += art.text2art("C64")
    s += "\n"
    s += art.text2art("THE")
    s += "\n"
    s += art.text2art("WORLD")
    s += "\n"
    s += art.text2art("BEST")
    s += "\n"
    s += art.text2art("SELLING")
    s += "\n"
    s += art.text2art("COMPUTER")
    s += "\n"
    s += art.text2art("OF")
    s += "\n"
    s += art.text2art("ALL")
    s += "\n"
    s += art.text2art("THE")
    s += "\n"
    s += art.text2art("TIME")
    s += "\n\n"
    s += "Oric 1"
    s += "\n"
    s += "MOS 6502A @ 1 MHz 16 Ko, 8 bits, K7, 150$, 220K units sold"
    s += "\n\n"
    s += "Thomson TO7"
    s += "\n"
    s += "Motorola 6809 @ 1 MHz 16 Ko, 8 bits, K7"
    s += "\n\n"
    s += art.text2art("1983")
    s += "\n\n"
    s += "Apple ][+"
    s += "\n"
    s += "MOS 6502 @ 1 MHz 64 Ko, 8 bits, FDD 5\"1/4, 1400$, 2.5M units sold"
    s += "\n"
    s += "Apple is the king of the Silicon Valley"
    s += "\n\n"
    s += load("ascii/apple2e.txt")
    s += "\n\n"
    s += "Atari 400XL & 800XL"
    s += "\n"
    s += "MOS 6502 @ 1.8 MHz 64 Ko, 8 bits, K7 & FDD 5\"1/4, 300$"
    s += "\n"
    s += "Atari success story before the crisis"
    s += "\n\n"
    s += load("ascii/atari800xl.txt")
    s += "\n\n"
    s += "IBM PC XT"
    s += "\n"
    s += "Intel 8088 @ 4.8 MHz 128 Ko, 8/16 bits, FDD 5\"1/4 + HD 10 Mo, 7000$\n"
    s += "250K units sold"
    s += "\n"
    s += "The first HDD 10 Mo"
    s += "\n\n"
    s += load("ascii/xt.txt")
    s += "\n\n"
    s += "Oric Atmos"
    s += "\n"
    s += "MOS 6502A @ 1 MHz 16 Ko, 8 bits, K7 + FDD 3\", 150$"
    s += "\n\n"
    s += "Matra Alice 32"
    s += "\n"
    s += "Motorola 6803 @ 0.9 MHz 16 Ko, 8 bits, K7, 150$"
    s += "\n\n"
    s += art.text2art("1984")
    s += "\n\n"
    s += "The all integrated era"
    s += "\n\n"
    s += "Apple Macintosh"
    s += "\n"
    s += "Motorola 68000 @ 7 MHz 128 Ko, 16/32 bits, FDD 3\"1/2, 2500$, 1M units sold"
    s += "\n"
    s += "Windows (not MS), mouse : The revolution"
    s += "\n\n"
    s += load("ascii/mac.txt")
    s += "\n"
    s += "The Floppy Disc 3\"1/2"
    s += "\n"
    s += load("ascii/floppy3.txt")
    s += "\n\n"
    s += "Amstrad CPC 464"
    s += "\n"
    s += "Zilog Z80 @ 4 MHz 64 Ko, 8 bits, K7 integrated\n"
    s += "400$ green monitor included, 2M units sold"
    s += "\n"
    s += "The begining of the Amstrad success story"
    s += "\n"
    s += "Alan Michael Sugar founder of AMS Trading (Amstrad)"
    s += "\n\n"
    s += load("ascii/464.txt")
    s += "\n\n"
    s += "Apple ][c"
    s += "\n"
    s += "MOS 65C02 @ 1 MHz 128 Ko, 8 bits, FDD 5\"1/4 integrated, 1300$\n"
    s += "1.6M units sold"
    s += "\n"
    s += load("ascii/apple2c.txt")
    s += "\n\n"
    s += "MSX"
    s += "\n"
    s += "Zilog Z80 @ 3.5 MHz 64 Ko, 8 bits, K7"
    s += "\n"
    s += "The Japanese standard (Toshiba, NEC, Philips, Sanyo, ...)"
    s += "\n\n"
    s += "IBM PC AT"
    s += "\n"
    s += "Intel 80286 @ 6 MHz 512 Ko, 16 bits, FDD 3\"1/2 + HD 20 Mo, 4000$"
    s += "\n"
    s += "The monster"
    s += "\n\n"
    s += load("ascii/at.txt")
    s += "\n\n"
    s += "Thomson TO7/70"
    s += "\n"
    s += "Motorola 6809 @ 1 MHz 48 Ko, 8 bits, K7 + FDD 5\" 1/4"
    s += "\n"
    s += "Le plan informatique de l'education nationale"
    s += "\n\n"
    s += "Thomson MO5"
    s += "\n"
    s += "Motorola 6809 @ 1 MHz 48 Ko, 8 bits, K7"
    s += "\n\n"
    s += art.text2art("1985")
    s += "\n\n"
    s += "Amstrad CPC 664"
    s += "\n"
    s += "Zilog Z80 @ 4 MHz 64 Ko, 8 bits, FDD 3\" integrated\n"
    s += "500$ color monitor included"
    s += "\n\n"
    s += load("ascii/664.txt")
    s += "\n\n"
    s += "Atari 520 ST"
    s += "\n"
    s += "Motorola 68000 @ 8 MHz 513 Ko, 16/32 bits, FDD 3\"1/2 integrated\n"
    s += "800$, 1.5M units sold"
    s += "\n\n"
    s += "The 16 bits era"
    s += "\n\n"
    s += load("ascii/520st.txt")
    s += "\n\n"
    s += "Amstrad CPC 6128"
    s += "\n"
    s += "Zilog Z80 @ 4 MHz 128 Ko, 8 bits, FDD 3\" integrated\n"
    s += "500$ color monitor included, 1M units sold"
    s += "\n\n"
    s += "My first computer"
    s += "\n\n"
    s += load("ascii/6128.txt")
    s += "\n\n"
    s += "Amstrad PCW 256 & 512"
    s += "\n"
    s += "Zilog Z80 @ 4 MHz 512 Ko, 8 bits, 2xFDD 3\" integrated\n"
    s += "250$ green monitor and printer included, 2M units sold"
    s += "\n\n"
    s += art.text2art("1986")
    s += "\n\n"
    s += "Apple Macintosh+"
    s += "\n"
    s += "Motorola 68000 @ 8 MHz 1 Mo, 16/32 bits, FDD 3\"1/2, 2600$\n"
    s += "2M units sold"
    s += "\n\n"
    s += load("ascii/macplus.txt")
    s += "\n\n"
    s += "Atari 1040 STF"
    s += "\n"
    s += "Motorola 68000 @ 8 MHz 1 Mo, 16/32 bits, FDD 3\"1/2 integrated\n"
    s += "800$, 1.5M units sold"
    s += "\n\n"
    s += load("ascii/1040st.txt")
    s += "\n\n"
    s += "Amstrad PC 1512 & 1640"
    s += "\n"
    s += "PC XT clone"
    s += "\n\n"
    s += "Apple ][ GS"
    s += "\n"
    s += "The last Apple ]["
    s += "\n\n"
    s += "Toshiba T1100"
    s += "\n"
    s += "The first PC laptop"
    s += "\n\n"
    s += load("ascii/laptop.txt")
    s += "\n\n"
    s += "IBM PC 386"
    s += "\n"
    s += "Intel 80386 @ 25-66 MHz 1-8 Mo, 32 bits, HD\n"
    s += "\n"
    s += "The first 32 bits processor with MS Windows 3.1\n"
    s += "\n\n"
    s += load("ascii/win31.txt")
    s += "\n\n"
    s += "Commodore Amiga 500"
    s += "\n"
    s += "Motorola 68000 @ 8 MHz 512 Ko, 16/32 bits, FDD 3\"1/2 integrated\n"
    s += "700$, 3M units sold"
    s += "\n\n"
    s += load("ascii/amiga.txt")
    s += "\n\n"
    s += art.text2art("1987")
    s += "\n\n"
    s += "Amstrad PPC 1512 & 1640"
    s += "\n"
    s += "The lowcost PC laptop transportable with LCD screen"
    s += "\n\n"
    s += "Apple Macintosh SE"
    s += "\n"
    s += "Motorola 68000 @ 8 MHz 1 Mo, 16/32 bits, HD, 5500$"
    s += "\n\n"
    s += art.text2art("1989")
    s += "\n\n"
    s += "Atari 1040 STE"
    s += "\n"
    s += "Motorola 68000 @ 8 MHz 1 Mo, 16/32 bits, FDD 3\"1/2 integrated\n"
    s += "800$, 750K units sold"
    s += "\n\n"
    s += load("ascii/1040ste.txt")
    s += "\n\n"
    s += "A lot of big commercial failure"
    s += "\n"
    s += "Amstrad CPC 6128+\n"
    s += "Atari TT & Falcon 030\n"
    s += "Matra Alice 90\n"
    s += "Thomson TO8 & TO9\n"
    s += "Commodore 128 (not a big failure)\n"
    s += "\n\n"
    s += art.text2art("1995")
    s += "\n\n"
    s += "Intel 486 CPU with MS Windows 95 & Office"
    s += "\n\n"
    s += art.text2art("1998")
    s += "\n\n"
    s += "Intel Pentium CPU with MS Windows 98 & office"
    s += "\n\n"
    s += "Author: Cyril Vincent @ www.CyrilVincent.com"
    s += "\n\n"
    s += load("ascii/cyril.txt")
    s += "\n\n"

    print(s)

    # break

    if sys.platform.startswith('win'):
        port = "COM3"
    else:
        port = "/dev/ttyUSB0"
    socket = serial.Serial(port, 1200, parity=serial.PARITY_EVEN, bytesize=7, timeout=5)
    rows = s.split("\n")
    for row in rows:
        b = row.center(80).rstrip().encode("ascii")
        socket.write(b)
        socket.write(b"\r\n")
        time.sleep(0.01)
    time.sleep(10)
    s = "\n\n"

