[Misc]
Width=235
Height=94
Title=Modem Diagnostics

[OnExit]
Item1=Defaults,Exitcode,2,SCREEN,faxrmail
;Item1=Defaults,Exitcode,2,SCREEN,ftpcheck

[Field Profile]
Field1="&Retry",defpushbutton,10,48,67,50,14
Field2="Cancel",pushbutton,2,140,67,50,14
Field3="Did not find a modem attached to your computer. You will not be able to register electronically.",ltext,-1,17,15,207,24
Field4="Please hit Retry to try again.",ltext,-1,17,44,213,18
