#!/bin/sh

APP_DIR=`dirname "$0"` export APP_DIR
cd $APP_DIR


# ECHO="Y" to echo all screen output to stdout
# 8K="Y" to use the 8K ROM with BASIC, Assembler and Monitor,
# otherwise just the monitor will be in ROM

# Replica 1
#java -DECHO="N" -D65C02="Y" -DROMFILE="65C02.rom.bin" -cp Pom1.jar pom1.Exec

# Pom 1
java -DECHO="Y" -DROMFILE="6502.rom.bin" -cp Pom1.jar pom1.Exec
